// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package repositories

import (
	"database/sql"
)

type User struct {
	ID        int64          `json:"id"`
	Email     string         `json:"email"`
	FirstName string         `json:"first_name"`
	LastName  string         `json:"last_name"`
	Avatar    sql.NullString `json:"avatar"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
}
