// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: users.sql

package repositories

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :execlastid
INSERT INTO users (
  id,email,first_name,last_name,avatar
) VALUES ( ?,?,?,?,? )
`

type CreateUserParams struct {
	ID        int64          `json:"id"`
	Email     string         `json:"email"`
	FirstName string         `json:"first_name"`
	LastName  string         `json:"last_name"`
	Avatar    sql.NullString `json:"avatar"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	result, err := q.exec(ctx, q.createUserStmt, createUser,
		arg.ID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.Avatar,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getCountManyUser = `-- name: GetCountManyUser :one
SELECT count(*) FROM users
WHERE deleted_at is null and (email like ? or first_name like ? or last_name like ?) LIMIT 1
`

type GetCountManyUserParams struct {
	Email     string `json:"email"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
}

func (q *Queries) GetCountManyUser(ctx context.Context, arg GetCountManyUserParams) (int64, error) {
	row := q.queryRow(ctx, q.getCountManyUserStmt, getCountManyUser, arg.Email, arg.FirstName, arg.LastName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getManyUser = `-- name: GetManyUser :many
SELECT id,email,first_name,last_name,avatar,created_at,updated_at FROM users
WHERE deleted_at is null and (email like ? or first_name like ? or last_name like ?)
ORDER BY id
LIMIT ?
OFFSET ?
`

type GetManyUserParams struct {
	Email     string `json:"email"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

type GetManyUserRow struct {
	ID        int64          `json:"id"`
	Email     string         `json:"email"`
	FirstName string         `json:"first_name"`
	LastName  string         `json:"last_name"`
	Avatar    sql.NullString `json:"avatar"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

func (q *Queries) GetManyUser(ctx context.Context, arg GetManyUserParams) ([]GetManyUserRow, error) {
	rows, err := q.query(ctx, q.getManyUserStmt, getManyUser,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetManyUserRow
	for rows.Next() {
		var i GetManyUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Avatar,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id,email,first_name,last_name,avatar,created_at,updated_at FROM users
WHERE id = ? and deleted_at is null LIMIT 1
`

type GetUserByIDRow struct {
	ID        int64          `json:"id"`
	Email     string         `json:"email"`
	FirstName string         `json:"first_name"`
	LastName  string         `json:"last_name"`
	Avatar    sql.NullString `json:"avatar"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.queryRow(ctx, q.getUserByIDStmt, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users 
SET deleted_at = now()
WHERE id = ? and deleted_at is null
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.softDeleteUserStmt, softDeleteUser, id)
	return err
}

const updatePartialUsers = `-- name: UpdatePartialUsers :execlastid
UPDATE users 
SET 
    email = COALESCE(?, email),
    first_name = COALESCE(?, first_name),
    last_name = COALESCE(?, last_name),
    avatar = COALESCE(?, avatar),
    updated_at = now()
WHERE id = ? and deleted_at is null
`

type UpdatePartialUsersParams struct {
	Email     string         `json:"email"`
	FirstName string         `json:"first_name"`
	LastName  string         `json:"last_name"`
	Avatar    sql.NullString `json:"avatar"`
	ID        int64          `json:"id"`
}

func (q *Queries) UpdatePartialUsers(ctx context.Context, arg UpdatePartialUsersParams) (int64, error) {
	result, err := q.exec(ctx, q.updatePartialUsersStmt, updatePartialUsers,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.Avatar,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}
