services:
  mysql_go_simple_user_crud:
    image: mysql:8.0.30
    container_name: mysql_go_simple_user_crud
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    networks:
      - go_simple_user_crud_network
    volumes:
      - mysql_go_simple_user_crud:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD : ROOT
       MYSQL_PASSWORD : SECRET
       MYSQL_USER : ADMIN
       MYSQL_DATABASE : go_simple_user_crud
  
  redis_go_simple_user_crud:
    image: redis:alpine3.16
    container_name: redis_go_simple_user_crud
    command: redis-server --save 60 1 --loglevel warning --requirepass 1234
    ports:
      - '6379:6379'
    networks:
      - go_simple_user_crud_network
    volumes:
      - redis_go_simple_user_crud:/data

volumes:
  mysql_go_simple_user_crud: {}
  redis_go_simple_user_crud: {}

networks:
  go_simple_user_crud_network: {}
  