services:
  simple_user_crud_app:
    build: .
    image: go-simple-user-crud
    container_name: go-simple-user-crud
    ports:
      - 8080:${apps_httpport}
    networks:
      - go_simple_user_crud_network
    env_file:
      - .env
    restart: on-failure
  
networks:
  go_simple_user_crud_network: {}
