// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package simpleusercrud

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createAuthorStmt, err = db.PrepareContext(ctx, createAuthor); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAuthor: %w", err)
	}
	if q.getCountManyUserStmt, err = db.PrepareContext(ctx, getCountManyUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetCountManyUser: %w", err)
	}
	if q.getManyUserStmt, err = db.PrepareContext(ctx, getManyUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetManyUser: %w", err)
	}
	if q.getUserStmt, err = db.PrepareContext(ctx, getUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetUser: %w", err)
	}
	if q.softDeleteUserStmt, err = db.PrepareContext(ctx, softDeleteUser); err != nil {
		return nil, fmt.Errorf("error preparing query SoftDeleteUser: %w", err)
	}
	if q.updatePartialUsersStmt, err = db.PrepareContext(ctx, updatePartialUsers); err != nil {
		return nil, fmt.Errorf("error preparing query UpdatePartialUsers: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createAuthorStmt != nil {
		if cerr := q.createAuthorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAuthorStmt: %w", cerr)
		}
	}
	if q.getCountManyUserStmt != nil {
		if cerr := q.getCountManyUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCountManyUserStmt: %w", cerr)
		}
	}
	if q.getManyUserStmt != nil {
		if cerr := q.getManyUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getManyUserStmt: %w", cerr)
		}
	}
	if q.getUserStmt != nil {
		if cerr := q.getUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserStmt: %w", cerr)
		}
	}
	if q.softDeleteUserStmt != nil {
		if cerr := q.softDeleteUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing softDeleteUserStmt: %w", cerr)
		}
	}
	if q.updatePartialUsersStmt != nil {
		if cerr := q.updatePartialUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updatePartialUsersStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                     DBTX
	tx                     *sql.Tx
	createAuthorStmt       *sql.Stmt
	getCountManyUserStmt   *sql.Stmt
	getManyUserStmt        *sql.Stmt
	getUserStmt            *sql.Stmt
	softDeleteUserStmt     *sql.Stmt
	updatePartialUsersStmt *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                     tx,
		tx:                     tx,
		createAuthorStmt:       q.createAuthorStmt,
		getCountManyUserStmt:   q.getCountManyUserStmt,
		getManyUserStmt:        q.getManyUserStmt,
		getUserStmt:            q.getUserStmt,
		softDeleteUserStmt:     q.softDeleteUserStmt,
		updatePartialUsersStmt: q.updatePartialUsersStmt,
	}
}
